apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lyricsapp-ingress
  namespace: mycujoo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: lyricsapp
          servicePort: 9100
